### ISSUE TITLE
Provide default services.yml, including APCu config

### ISSUE THREAD

**Issue by danepowell** [acquia/bolt#40]
On one of our ACE sites, we are seeing failing page loads with this error:
"Warning: apcu_store(): Unable to allocate memory for pool. in Drupal\Core\Cache\ApcuBackend->set() (line 177 of core/lib/Drupal/Core/Cache/ApcuBackend.php)."

According to support, this is due to Drupal 8 using APCu for some types of caching, which has a hardcoded memory limit that is too low.

The "strongly recommended" fix is to add the following to services.yml to tell Drupal to use the database instead of APCu for these types of caching:

````
services:
  cache.backend.chainedfast:
    class: Drupal\Core\Cache\ChainedFastBackendFactory
    arguments: ['@settings', 'cache.backend.database', 'cache.backend.database']
    calls:
      - [setContainer, ['@service_container']]
````

The long-term fix is to use Memcache, but memcache is not currently stable or recommended for D8.

Seems like Bolt should provide services.yml with this config by default.

We're testing this fix right now, and if it works will report back and try to open a PR.
